# Alertmanager Configuration
global:
  resolve_timeout: 5m
  # SMTP Configuration (Email Notifications)
  smtp_smarthost: 'smtp.gmail.com:587'
  smtp_from: 's94094838@gmail.com'
  smtp_auth_username: 's94094838@gmail.com'
  smtp_auth_password: 'your-app-password'
  smtp_require_tls: true

# Templates for notifications
templates:
  - '/etc/alertmanager/*.tmpl'

# Route configuration
route:
  group_by: ['alertname', 'cluster', 'service']
  group_wait: 10s
  group_interval: 10s
  repeat_interval: 12h
  receiver: 'default'
  
  # Child routes
  routes:
    # Critical alerts
    - match:
        severity: critical
      receiver: 'critical-alerts'
      continue: true
      group_wait: 5s
      repeat_interval: 3h

    # Warning alerts
    - match:
        severity: warning
      receiver: 'warning-alerts'
      group_wait: 10s
      repeat_interval: 12h

    # System alerts
    - match:
        category: system
      receiver: 'system-team'

    # Application alerts
    - match:
        category: application
      receiver: 'app-team'

# Receivers configuration
receivers:
  # Default receiver
  - name: 'default'
    email_configs:
      - to: 's94094838@gmail.com'
        send_resolved: true
        headers:
          Subject: '[Monitoring] Alert: {{ .GroupLabels.alertname }}'

  # Critical alerts receiver
  - name: 'critical-alerts'
    email_configs:
      - to: 's94094838@gmail.com'
        send_resolved: true
        headers:
          Subject: '[CRITICAL] {{ .GroupLabels.alertname }}'
    # Slack configuration (uncomment and configure)
    # slack_configs:
    #   - api_url: 'https://hooks.slack.com/services/YOUR/SLACK/WEBHOOK'
    #     channel: '#critical-alerts'
    #     title: 'Critical Alert: {{ .GroupLabels.alertname }}'
    #     text: '{{ range .Alerts }}{{ .Annotations.description }}{{ end }}'

  # Warning alerts receiver
  - name: 'warning-alerts'
    email_configs:
      - to: 's94094838@gmail.com'
        send_resolved: true
        headers:
          Subject: '[WARNING] {{ .GroupLabels.alertname }}'

  # System team receiver
  - name: 'system-team'
    email_configs:
      - to: 's94094838@gmail.com'
        send_resolved: true

  # Application team receiver
  - name: 'app-team'
    email_configs:
      - to: 's94094838@gmail.com'
        send_resolved: true

# Inhibition rules (suppress alerts)
inhibit_rules:
  # Suppress warning if critical alert is firing
  - source_match:
      severity: 'critical'
    target_match:
      severity: 'warning'
    equal: ['alertname', 'instance']

  # Suppress all alerts if instance is down
  - source_match:
      alertname: 'InstanceDown'
    target_match_re:
      severity: '.*'
    equal: ['instance']
