# Prometheus Alerting Rules
groups:
  - name: system_alerts
    interval: 30s
    rules:
      # High CPU Usage Alert
      - alert: HighCPUUsage
        expr: 100 - (avg by(instance) (rate(node_cpu_seconds_total{mode="idle"}[5m])) * 100) > 80
        for: 5m
        labels:
          severity: warning
          category: system
        annotations:
          summary: "High CPU usage detected on {{ $labels.instance }}"
          description: "CPU usage is above 80% (current value: {{ $value }}%)"

      # Critical CPU Usage Alert
      - alert: CriticalCPUUsage
        expr: 100 - (avg by(instance) (rate(node_cpu_seconds_total{mode="idle"}[5m])) * 100) > 95
        for: 2m
        labels:
          severity: critical
          category: system
        annotations:
          summary: "Critical CPU usage on {{ $labels.instance }}"
          description: "CPU usage is critically high at {{ $value }}%"

      # High Memory Usage Alert
      - alert: HighMemoryUsage
        expr: (1 - (node_memory_MemAvailable_bytes / node_memory_MemTotal_bytes)) * 100 > 80
        for: 5m
        labels:
          severity: warning
          category: system
        annotations:
          summary: "High memory usage on {{ $labels.instance }}"
          description: "Memory usage is above 80% (current value: {{ $value }}%)"

      # Critical Memory Usage Alert
      - alert: CriticalMemoryUsage
        expr: (1 - (node_memory_MemAvailable_bytes / node_memory_MemTotal_bytes)) * 100 > 95
        for: 2m
        labels:
          severity: critical
          category: system
        annotations:
          summary: "Critical memory usage on {{ $labels.instance }}"
          description: "Memory usage is critically high at {{ $value }}%"

      # Low Disk Space Alert
      - alert: LowDiskSpace
        expr: (node_filesystem_avail_bytes{mountpoint="/"} / node_filesystem_size_bytes{mountpoint="/"}) * 100 < 20
        for: 5m
        labels:
          severity: warning
          category: storage
        annotations:
          summary: "Low disk space on {{ $labels.instance }}"
          description: "Less than 20% disk space available (current: {{ $value }}%)"

      # Critical Disk Space Alert
      - alert: CriticalDiskSpace
        expr: (node_filesystem_avail_bytes{mountpoint="/"} / node_filesystem_size_bytes{mountpoint="/"}) * 100 < 10
        for: 2m
        labels:
          severity: critical
          category: storage
        annotations:
          summary: "Critical disk space on {{ $labels.instance }}"
          description: "Less than 10% disk space available (current: {{ $value }}%)"

      # Instance Down Alert
      - alert: InstanceDown
        expr: up == 0
        for: 1m
        labels:
          severity: critical
          category: availability
        annotations:
          summary: "Instance {{ $labels.instance }} is down"
          description: "{{ $labels.job }} on {{ $labels.instance }} has been down for more than 1 minute"

  - name: application_alerts
    interval: 30s
    rules:
      # High Request Rate
      - alert: HighRequestRate
        expr: rate(http_requests_total[5m]) > 1000
        for: 5m
        labels:
          severity: warning
          category: application
        annotations:
          summary: "High request rate detected"
          description: "Request rate is {{ $value }} requests/second"

      # High Error Rate
      - alert: HighErrorRate
        expr: (rate(http_requests_total{status=~"5.."}[5m]) / rate(http_requests_total[5m])) * 100 > 5
        for: 5m
        labels:
          severity: critical
          category: application
        annotations:
          summary: "High error rate detected"
          description: "Error rate is {{ $value }}%"

      # Slow Response Time
      - alert: SlowResponseTime
        expr: histogram_quantile(0.95, rate(http_request_duration_seconds_bucket[5m])) > 2
        for: 5m
        labels:
          severity: warning
          category: performance
        annotations:
          summary: "Slow response time detected"
          description: "95th percentile response time is {{ $value }} seconds"

  - name: nginx_alerts
    interval: 30s
    rules:
      # Nginx Down
      - alert: NginxDown
        expr: nginx_up == 0
        for: 1m
        labels:
          severity: critical
          category: service
        annotations:
          summary: "Nginx is down"
          description: "Nginx service on {{ $labels.instance }} is not responding"

      # High Nginx Connections
      - alert: HighNginxConnections
        expr: nginx_connections_active > 1000
        for: 5m
        labels:
          severity: warning
          category: service
        annotations:
          summary: "High number of Nginx connections"
          description: "Active connections: {{ $value }}"

  - name: container_alerts
    interval: 30s
    rules:
      # High Container CPU
      - alert: HighContainerCPU
        expr: rate(container_cpu_usage_seconds_total{container!=""}[5m]) * 100 > 80
        for: 5m
        labels:
          severity: warning
          category: container
        annotations:
          summary: "High CPU usage in container {{ $labels.name }}"
          description: "Container CPU usage is {{ $value }}%"

      # High Container Memory
      - alert: HighContainerMemory
        expr: (container_memory_usage_bytes{container!=""} / container_spec_memory_limit_bytes{container!=""}) * 100 > 80
        for: 5m
        labels:
          severity: warning
          category: container
        annotations:
          summary: "High memory usage in container {{ $labels.name }}"
          description: "Container memory usage is {{ $value }}%"

      # Container Restart
      - alert: ContainerRestart
        expr: rate(container_restart_count[15m]) > 0
        for: 1m
        labels:
          severity: warning
          category: container
        annotations:
          summary: "Container {{ $labels.name }} restarted"
          description: "Container has restarted {{ $value }} times in the last 15 minutes"
